services:

  app:
    image: blog-frontend-dev
    pull_policy: never
    build:
      context: ./blog-frontend/
      dockerfile: dev.Dockerfile
    volumes:
      - ./blog-frontend/:/usr/src/app
      - /usr/src/app/node_modules
    container_name: blog-frontend-dev

  server:
    image: blog-backend-dev
    pull_policy: never
    build:
      context: ./blog-backend/
      dockerfile: dev.Dockerfile
    volumes:
      - ./blog-backend/:/usr/src/app
      - /usr/src/app/node_modules
    container_name: blog-backend-dev
    env_file: ./blog-backend/.env

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app
